GestionStock.ASP/Models/Order/Forms/AddOrderLineModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GestionStock.ASP.Models.Order.Forms
{
    public class AddOrderLineModel
    {
        [Required]
        [Display(Name = "Produit")]
        public string ProductRef { get; set; }

        [Required]
        [Range(-9999999, 9999999)]
        [Display(Name = "Quantité")]
        public int Quantity { get; set; }
    }
}

GestionStock.ASP/Models/Order/Forms/CreateOrderModel.cs
using GestionStock.ASP.Models.Customer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionStock.ASP.Models.Order.Forms
{
    public class CreateOrderModel
    {
        [Required]
        [Display(Name = "Client")]
        public string CustomerRef { get; set; }
        public IEnumerable<SelectListItem> AllCustomers { get; set; }
    }
}

GestionStock.ASP/Models/Order/Forms/EditOrderModel.cs
using GestionStock.DAL.Abstractions.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GestionStock.ASP.Models.Order.Forms
{
    public class EditOrderModel
    {
        #region Display only
        [Display(Name = "Référence")]
        public string Reference { get; set; }

        [Display(Name = "Client")]
        public string CustomerRef { get; set; }

        public decimal Total { get; set; }

        [Display(Name = "État")]
        public OrderStatus Status { get; set; }

        public DateTime Date { get; set; }

        public List<OrderLineModel> OrderLines { get; set; }

        #endregion

        #region Form for adding new Line
        public AddOrderLineModel NewLine { get; set; } = new AddOrderLineModel(); 
        #endregion
    }
}

GestionStock.ASP/Models/Order/OrderIndexModel.cs
using GestionStock.ASP.Validators;
using GestionStock.DAL.Abstractions.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestionStock.ASP.Models.Order
{
    public class OrderIndexModel : IndexModelBase<OrderModel>
    {
        public OrderIndexModel()
        {

        }
        public OrderIndexModel(IEnumerable<OrderModel> results)
            : base(results)
        {

        }

        [Display(Name = "Référence")]
        public string Reference { get; set; }
        [Display(Name = "Client")]
        public string CustomerRef { get; set; }
        [Display(Name = "États")]
        public List<OrderStatus> SelectedStatuses { get; set; } = new List<OrderStatus>() 
        {
            OrderStatus.InProgress,
            OrderStatus.Pending,
        };

        [DataType(DataType.Date)]
        [Display(Name = "Entre le")]
        public DateTime? FromDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "et le")]
        [DateComparerValidator(nameof(FromDate))]
        public DateTime? ToDate { get; set; }

        public IEnumerable<SelectListItem> AllCustomers { get; set; }
        public IEnumerable<SelectListItem> AllStatuses { get; set; }
    }
}

GestionStock.ASP/Models/Order/OrderLineModel.cs
using GestionStock.ASP.Models.Product;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GestionStock.ASP.Models.Order
{
    public class OrderLineModel
    {
        public int Id { get; set; }

        [Display(Name = "Quantité")]
        public int Quantity { get; set; }

        [Display(Name = "Produit")]
        public string ProductRef { get; set; }

        public string OrderRef { get; set; }

        [Display(Name = "Prix unitaire")]
        public decimal UnitPrice { get; set; }

        [Display(Name = "Prix")]
        public decimal LinePrice { get; set; }
    }
}

GestionStock.ASP/Models/Order/OrderModel.cs
using GestionStock.DAL.Abstractions.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace GestionStock.ASP.Models.Order
{
    public class OrderModel
    {
        [Display(Name = "Référence")]
        public string Reference { get; set; }
        [Display(Name = "État")]
        public OrderStatus Status { get; set; }

        public DateTime Date { get; set; }
        [Display(Name = "Client")]
        public string CustomerRef { get; set; }
        public decimal Total { get; set; }
    }
}

GestionStock.ASP/Controllers/OrderController.cs
using GestionStock.ASP.Models.Order;
using GestionStock.ASP.Models.Order.Forms;
using GestionStock.ASP.Utils;
using GestionStock.BLL.BusinessObjects;
using GestionStock.BLL.Exceptions;
using GestionStock.BLL.Services;
using GestionStock.DAL.Abstractions.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace GestionStock.ASP.Controllers
{
    [Authorization(UserRole.Admin, UserRole.Seller)]
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private ICustomerService _customerService;

        public OrderController(IOrderService orderService, ICustomerService customerService)
        {
            _orderService = orderService;
            _customerService = customerService;
        }

        public ActionResult Index(OrderIndexModel model)
        {

            model.Results = _orderService
                .FindWithFilters(model.Offset, model.Limit, model.Reference,model.CustomerRef, model.SelectedStatuses,model.FromDate,model.ToDate)
                .Select(o => new OrderModel {
                        Reference = o.Reference,
                        CustomerRef = o.CustomerRef,
                        Date = o.Date,
                        Status = o.Status,
                        Total = o.Total,
                    }
                );
            model.AllCustomers = GetSelectFromCustomers(true);
            model.AllStatuses = SelectUtils.GetSelectFromEnum<OrderStatus>();
            return View(model);
        }

        public ActionResult Create()
        {
            CreateOrderModel form = new CreateOrderModel
            {
                AllCustomers = GetSelectFromCustomers()
            };
            return View(form);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateOrderModel form)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    string reference = _orderService.Add(new OrderBO(form.CustomerRef));
                    TempData.Info("Continuer la commande");
                    return RedirectToAction("Edit", new { id = reference });
                }
                catch(EntityNotFoundException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }
            form.AllCustomers = GetSelectFromCustomers();
            return View(form);
        }

        public ActionResult Edit(string id)
        {
            try
            {
                OrderBO order = _orderService.FindOneWithOrderLines(id);
                EditOrderModel model = new EditOrderModel
                {
                    Reference = order.Reference,
                    CustomerRef = order.CustomerRef,
                    Status = order.Status,
                    Date = order.Date,
                    Total = order.Total,
                    OrderLines = order.OrderLines.Select(ol => new OrderLineModel
                    {
                        Id = ol.Id,
                        ProductRef = ol.ProductRef,
                        Quantity = ol.Quantity,
                        UnitPrice = ol.UnitPrice,
                        LinePrice = ol.LinePrice,
                    }).ToList(),
                };
                return View(model);
            }
            catch (EntityNotFoundException)
            {
                return new HttpNotFoundResult();
            }
        }
        public ActionResult Pend(string id)
        {
            return ChangeStatus(id, OrderStatus.Pending);
        }

        [Authorization(UserRole.Admin)]
        public ActionResult Close(string id)
        {
            return ChangeStatus(id, OrderStatus.Closed);
        }

        [Authorization(UserRole.Admin)]
        public ActionResult Cancel(string id)
        {
            return ChangeStatus(id, OrderStatus.Canceled);
        }

        [HttpPost] // cannot enable put method // ask michael or thierry
        public ActionResult Edit(string id, AddOrderLineModel form) 
        {
            if(ModelState.IsValid) // cannot validate model in ajax // ask michael or thierry
            {
                try
                {
                    IEnumerable<OrderLineModel> lines = _orderService.UpdateLines(id, form.ProductRef, form.Quantity)
                        .Select(ol => new OrderLineModel
                        {
                            Id = ol.Id,
                            OrderRef = ol.OrderRef,
                            ProductRef = ol.ProductRef,
                            Quantity = ol.Quantity,
                            UnitPrice = ol.UnitPrice,
                            LinePrice = ol.LinePrice,
                        });
                    // if not called in ajax
                    // no need to map lines and return Redirect or View instead
                    // TempData["success"] = "Enregistrement OK";
                    // return RedirectToAction("Edit", new { id = reference });
                    return Json(new { lines });
                }
                catch (EntityNotFoundException ex)
                {
                    if(ex.Property == null)
                    {
                        return new HttpNotFoundResult();
                    }
                    else
                    {
                        // ModelState.AddModelError(ex.Property, ex.Message);
                        return new HttpStatusCodeResult(400, "Le produit demandé est introuvable");
                    }
                }
                catch(InvalidOperationException)
                {
                    // TempData["error"] = "Vous ne pouvez pas modifier cette commande";
                    return new HttpStatusCodeResult(400, "Vous ne pouvez pas modifier cette commande");
                }
            }
            // return View(model);
            return new HttpStatusCodeResult(400, "Les informations fournies ne sont pas valides");
        }

        private IEnumerable<SelectListItem> GetSelectFromCustomers(bool emptyLine = false)
        {
            IEnumerable<SelectListItem> lines = _customerService.FindAllActive().Select(c => new SelectListItem
            {
                Value = c.Reference,
                Text = c.Label,
            });
            return emptyLine ? SelectUtils.GetOneEmptyLine().Concat(lines) : lines;
        }

        private ActionResult ChangeStatus(string id, OrderStatus status)
        {
            try
            {
                _orderService.ChangeStatus(id, status);
                TempData.Success("Operation OK");
                return RedirectToAction("Index");
            }
            catch (EntityNotFoundException)
            {
                return new HttpNotFoundResult();
            }
            catch (InvalidStatusException ex)
            {
                TempData.Error(ex.Message);
            }
            catch(EmptyOrderException)
            {
                TempData.Error($"Votre commande ne peut pas être vide");
            }
            catch (NegativeStockException ex)
            {
                TempData.Error($"Vous dépassez la limite des stocks du produit ({ex.ProductRef}) max: {ex.ActualStock}");
            }
            catch (SmtpException)
            {
                TempData.Error($"Nous n'avons pas pu envoyer les emails veuillez revérifier l'email du client");
            }
            return RedirectToAction("Edit", new { id });
        }
    }
}

GestionStock.ASP/Controllers/ProductController.cs
using GestionStock.ASP.Models.Product;
using GestionStock.ASP.Models.Product.Forms;
using GestionStock.ASP.Utils;
using GestionStock.BLL.BusinessObjects;
using GestionStock.BLL.Exceptions;
using GestionStock.BLL.Services;
using GestionStock.DAL.Abstractions.Enums;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GestionStock.ASP.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [Authorization(UserRole.Admin, UserRole.Seller)]
        public ActionResult Index(ProductIndexModel model)
        {
            model.Results = _productService.FindWithFilters(model.Offset, model.Limit, model.Search)
                .Select(p => new ProductModel
                {
                    Reference = p.Reference,
                    Name = p.Name,
                    Price = p.Price,
                    Stock = p.Stock,
                });
            model.Count = _productService.CountWithFilters(model.Search);
            return View(model);
        }

        [Authorization(UserRole.Admin)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorization(UserRole.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateProductModel form)
        {
            if (ModelState.IsValid)
            {
                _productService.Add(new ProductBO(form.Name, form.Description, form.Price, form.Stock));
                TempData.Success("Ajout OK");
                return RedirectToAction("Index");
            }
            return View(form);
        }

        [Authorization(UserRole.Admin)]
        public ActionResult Edit(string id)
        {
            try
            {
                ProductBO product = _productService.FindOne(id);
                TempData.Success("Modification OK");
                return View(new EditProductModel
                {
                    Reference = product.Reference,
                    Name = product.Name,
                    Description = product.Description,
                    Price = product.Price,
                    Stock = product.Stock,
                });
            }
            catch (EntityNotFoundException)
            {
                return new HttpNotFoundResult();
            }
        }

        [HttpPost]
        [Authorization(UserRole.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, EditProductModel form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _productService.Edit(new ProductBO(id, form.Name, form.Description, form.Price), form.UpdateStock);
                    TempData.Success("Ajout OK");
                    return RedirectToAction("Index");
                }
                catch (EntityNotFoundException)
                {
                    return new HttpNotFoundResult();
                }
                catch(NegativeStockException ex)
                {
                    form.Stock = ex.ActualStock;
                    ModelState.AddModelError("UpdateStock", "The stock cannot be negative");
                }
            }
            return View(form);
        }

        [Authorization(UserRole.Admin)]
        public ActionResult Delete(string id)
        {
            try
            {
                _productService.Delete(id);
                TempData.Success($"Le produit ({id}) a été supprimé");
            }
            catch (EntityNotFoundException)
            {
                return new HttpNotFoundResult();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorization(UserRole.Admin, UserRole.Seller)]
        public ActionResult Search(string search)
        {
            IEnumerable<ProductModel> Results = _productService.FindWithFilters(0, 10, search)
                .Select(p => new ProductModel
                {
                    Reference = p.Reference,
                    Name = p.Name,
                    Price = p.Price,
                    Stock = p.Stock,
                    Label = p.Label,
                });
            return Json(Results, JsonRequestBehavior.AllowGet);
        }
    }
}

GestionStock.ASP/Views/Order/Create.cshtml
@model GestionStock.ASP.Models.Order.Forms.CreateOrderModel

@{
    ViewBag.Title = "Create";
}

<a href="@Url.Action("Index")"><i class="back-btn fa fa-arrow-circle-left"></i></a>

<h4>Nouvelle Commande</h4>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerRef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CustomerRef, Model.AllCustomers, new { @class = "form-control select2" })
                @Html.ValidationMessageFor(model => model.CustomerRef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionStock.ASP/Views/Order/Edit.cshtml
@model GestionStock.ASP.Models.Order.Forms.EditOrderModel

@{
    ViewBag.Title = "Edit";
}

<a href="@Url.Action("Index")"><i class="back-btn fa fa-arrow-circle-left"></i></a>
<h4>Modification de la commande @Model.Reference</h4>
<hr />

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerRef, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.CustomerRef, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
        </div>
    </div>
</div>

<h4>Lignes de commande</h4>
<hr />
@if (Model.Status == OrderStatus.InProgress)
{
    @Html.Partial("_CreateEditLine", Model.NewLine)
    @Html.Partial("_OrderLinesTable", Model.OrderLines)
}
else
{
    @Html.Partial("_OrderLinesTableReadonly", Model.OrderLines)
}


<div class="row">
    <div class="col-md-offset-8 col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 order-actions">
        <a class="btn btn-primary" href="@Url.Action("Index")"><i class="fa fa-arrow-circle-left"></i> Revenir à la page d'index</a>
        @if ((int)Model.Status < 1)
        {
            <a class="btn btn-info" href="@Url.Action("Pend", new { Id = Model.Reference })"><i class="fa fa-check"></i> Terminer la commande</a>
        }
        @if ((int)Model.Status < 2 && Session.HasAnyRole(UserRole.Admin))
        {
            <a class="btn btn-success need-confirm" href="@Url.Action("Close", new { Id = Model.Reference })"><i class="fas fa-check-circle"></i> Valider le paiement</a>
            <a class="btn btn-danger need-confirm" href="@Url.Action("Cancel", new { Id = Model.Reference })"><i class="fas fa-exclamation-triangle"></i> Annuler la commande</a>
        }
    </div>
</div>

<datalist id="ProductRefList">
</datalist>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.25.0/axios.min.js"></script>
    @if (Model.Status == OrderStatus.InProgress)
    {
        <script>
            // for table update
            const url = '@Url.Action("Edit", "Order", new { Id = Model.Reference })';
            const form = document.querySelector('form');
            const productRefInput = document.getElementById('ProductRef');
            const quantityInput = document.getElementById('Quantity');
            const tbody = document.getElementById('orderLinesTbody');
            const deleteButtons = document.querySelectorAll('.delete-btn');
            const totalInput = document.getElementById('Total');

            const drawLines = ({ data }) => {
                // if you don't want to render the view u can just call window.location.reload;
                tbody.innerHTML = '';
                for (let item of data.lines) {
                    const tr = createLine(item);
                    tbody.appendChild(tr);
                }
                const sum = data.lines.reduce((res, item) => {
                    res += item.LinePrice;
                    return res;
                }, 0);
                totalInput.value = sum;

                productRefInput.value = '';
                quantityInput.value = 0;

                productRefInput.focus();
                searchProducts();
                toastr.success('Enregistrement OK');
            }

            const deleteLine = e => {
                const productRef = e.target.getAttribute('data-ref');
                axios.post(url, {
                    productRef,
                    quantity: 0
                }).then(drawLines)
                .catch(xhr => {
                    toastr.error('Une erreur est survenue');
                });
            }

            const createLine = (item) => {
                const tr = document.createElement('tr');
                const productRefTd = document.createElement('td');
                const quantityTd = document.createElement('td');
                const unitPriceTd = document.createElement('td');
                const linePriceTd = document.createElement('td');
                const actionsTd = document.createElement('td');

                tr.appendChild(productRefTd);
                tr.appendChild(quantityTd);
                tr.appendChild(unitPriceTd);
                tr.appendChild(linePriceTd);
                tr.appendChild(actionsTd);

                productRefTd.innerText = item.ProductRef;
                quantityTd.innerText = item.Quantity;
                unitPriceTd.innerText = item.UnitPrice;
                linePriceTd.innerText = item.LinePrice;

                const iTrash = document.createElement('i');
                const aDelete = document.createElement('a');
                iTrash.classList.add('fa', 'fa-trash');
                aDelete.classList.add('btn', 'btn-xs', 'btn-danger', 'delete-btn');
                aDelete.setAttribute('data-ref', item.ProductRef);
                aDelete.appendChild(iTrash);
                aDelete.addEventListener('click', deleteLine);
                actionsTd.appendChild(aDelete);

                return tr;
            }

            form.addEventListener('submit', e => {
                e.preventDefault();
                if (!productRefInput.value || !parseInt(quantityInput.value)) {
                    toastr.error('Vérifiez vos données');
                    return;
                }
                axios.post(url, {
                    productRef: productRefInput.value,
                    quantity: parseInt(quantityInput.value)
                }).then(drawLines)
                .catch(xhr => {
                    toastr.error('Une erreur est survenue');
                });
            });

            for (let btn of deleteButtons) {
                btn.addEventListener('click', deleteLine);
            }
                // for dynamic search
            const productRefList = document.getElementById('ProductRefList');
            const productUrl = '@Url.Action("Search", "Product")';

            const searchProducts = () => {
                const value = productRefInput.value;
                axios.get(productUrl + (value ? '?search=' + value : '')).then(({ data }) => {
                    productRefList.innerHTML = '';
                    for (let item of data) {
                        const option = document.createElement('option');
                        option.setAttribute('value', item.Reference);
                        option.innerText = item.Label;
                        productRefList.appendChild(option);
                    }
                });
            }

            productRefInput.addEventListener('input', searchProducts);
            searchProducts();
        </script>
    }

    <script>
        const btns = document.querySelectorAll('.need-confirm');
        for (let btn of btns) {
            btn.addEventListener('click', e => {
                e.preventDefault();
                confirmBox.show({
                    title: 'Demande de confirmation.',
                    content: `<p>Voulez-vous poursuivre cette opération?</p>
                                          <p><bold><i class="fas fa-exclamation-triangle"></i> Il ne sera plus possible de revenir en arrière après ce changement !</bold></p>`,
                    onConfirm: () => {
                        // besoin de supprimer l'event des icons pour être sûr
                        // que e.target soit bien le lien "<a>"
                        // voir css
                        window.location.href = e.target.getAttribute('href');
                    }
                });
            });
        }
    </script>
}

GestionStock.ASP/Views/Order/Index.cshtml
@model GestionStock.ASP.Models.Order.OrderIndexModel
@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Nouvelle", "Create", null, new { @class = "btn btn-primary" })
</p>

<form method="get">
    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Reference)
            @Html.EditorFor(m => m.Reference, new { htmlAttributes = new { @class = "form-control", autofocus = true, placeholder = "reference" } })
            @Html.ValidationMessageFor(m => m.Reference, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.CustomerRef)
            @Html.DropDownListFor(m => m.CustomerRef, Model.AllCustomers, new { @class = "form-control select2" })
            @Html.ValidationMessageFor(m => m.CustomerRef, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.FromDate)
            @Html.EditorFor(m => m.FromDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Depuis" } })
            @Html.ValidationMessageFor(m => m.FromDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.ToDate)
            @Html.EditorFor(m => m.ToDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Jusqu'à" } })
            @Html.ValidationMessageFor(m => m.ToDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.SelectedStatuses)
            @Html.ListBoxFor(m => m.SelectedStatuses, Model.AllStatuses, new { @class = "form-control select2-multiple", multiple = true })
            @Html.ValidationMessageFor(m => m.SelectedStatuses, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <a href="@Url.Action("Index")" class="btn btn-default">Reset <i class="fas fa-undo"></i></a>
            <button class="btn btn-info">Rechercher <i class="fa fa-search"></i></button>
        </div>
    </div>
</form>

@* Pas de pagination sur la page de recherche des commandes on affiche que les 10 premiers résultats *@

@if (Model.Results.Count() > 0)
{
    @Html.Partial("_Table", Model.Results)
}
else
{
    <p>Aucun résultat</p>
}

GestionStock.ASP/Views/Order/_CreateEditLine.cshtml
@model GestionStock.ASP.Models.Order.Forms.AddOrderLineModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @* use dropdown list if you dont want to make ajax calls *@
                @Html.LabelFor(model => model.ProductRef, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.ProductRef, new { htmlAttributes = new { @class = "form-control", list = "ProductRefList" } })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group" style="text-align:right">
                <input type="submit" value="Ajouter/Modifier" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

GestionStock.ASP/Views/Order/_OrderLinesTable.cshtml
@model IEnumerable<GestionStock.ASP.Models.Order.OrderLineModel>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductRef)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinePrice)
            </th>
            <th>
            <th></th>
        </tr>
        <tbody id="orderLinesTbody">

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductRef)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LinePrice)
                </td>
                <td>
                    <a class="btn btn-xs btn-danger delete-btn" data-ref="@item.ProductRef"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        }

        </tbody>   
    </table>