GestionStock.ASP/Areas/Security/Models/Authentication/forms/EmailModel.cs
using System.ComponentModel.DataAnnotations;

namespace GestionStock.ASP.Areas.Security.Models.Authentication.forms
{
    public class EmailModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

GestionStock.ASP/Areas/Security/Models/Authentication/forms/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace GestionStock.ASP.Areas.Security.Models.Authentication.forms
{
    public class LoginModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Mot de passe")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

GestionStock.ASP/Areas/Security/Models/Authentication/forms/ResetPasswordModel.cs
using System.ComponentModel.DataAnnotations;

namespace GestionStock.ASP.Areas.Security.Models.Authentication.forms
{
    public class ResetPasswordModel
    {
        [Required]
        [RegularExpression(
            "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&#])[A-Za-z\\d@$!%*?&#]{8,}$", 
             ErrorMessage = "Votre mot de passe doit contenir au moins une minuscule, une majuscule, un chiffre, un caractère spécial et avoir une longueur minimal de 8 caractères"
        )]
        [Display(Name = "Nouveau mot de passe")]
        [DataType(DataType.Password)]
        public string NewPasssword { get; set; }

        [Required]
        [Compare(nameof(NewPasssword))]
        [Display(Name = "Confirmer votre mot de passe")]
        [DataType(DataType.Password)]
        public string ConfirmNewPassword { get; set; }
    }
}

GestionStock.ASP/Areas/Security/Controllers/AuthenticationController.cs
using GestionStock.ASP.Areas.Security.Models.Authentication.forms;
using GestionStock.ASP.Utils;
using GestionStock.BLL.BusinessObjects;
using GestionStock.BLL.Exceptions;
using GestionStock.BLL.Services;
using GestionStock.DAL.Abstractions.Enums;
using System;
using System.Net.Mail;
using System.Web.Mvc;

namespace GestionStock.ASP.Areas.Security.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthService _loginService;

        public AuthenticationController(IAuthService loginService)
        {
            _loginService = loginService;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel form)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    UserBO user = _loginService.Login(form.Email, form.Password);
                    Session.Start(user.Id, user.Email, user.Role);
                    TempData.Info("Bienvenue");
                    if(user.Role == UserRole.Admin)
                    {
                        return RedirectToAction("Index", "Dashboard");
                    }
                    else if(user.Role == UserRole.Seller) 
                    {
                        return RedirectToAction("Index", "Customer");
                    }
                }
                catch(InvalidCredentialsException)
                {
                    TempData.Error("Invalid Credentials");
                }
            }
            return View(form);
        }

        public ActionResult AskResetPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AskResetPassword(EmailModel form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _loginService.AskResetPassword(form.Email);
                    TempData.Success("Un email vous a été envoyé");
                    return RedirectToAction("Login");
                }
                catch (EntityNotFoundException)
                {
                    TempData.Error("Email introuvable");
                }
                catch (SmtpException)
                {
                    TempData.Error("Envoi email impossible");
                }
            }
            return View(form);
        }

        public ActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost()]
        [Route("ResetPassword?token={token}")]
        public ActionResult ResetPassword(string token, ResetPasswordModel form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _loginService.ResetPassword(token, form.NewPasssword);
                    TempData.Success("Votre mot de passe a été mis à jour");
                    return RedirectToAction("Login");
                }
                catch (Exception) // jwt Exception
                {
                    TempData.Error("Invalid token");
                }
            }
            return View(form);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

GestionStock.ASP/Areas/Security/Views/Authentication/AskResetPassword.cshtml
@model GestionStock.ASP.Areas.Security.Models.Authentication.forms.EmailModel

@{
    ViewBag.Title = "Rrenseigner votre adresse email";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Login", "Authentication", new { Area = "Security" })">Revenir sur la page de login</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionStock.ASP/Areas/Security/Views/Authentication/Login.cshtml
@model GestionStock.ASP.Areas.Security.Models.Authentication.forms.LoginModel

@{
    ViewBag.Title = "Login";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Se connecter" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("AskResetPassword", "Authentication")">J'ai oublié mon mot de passe</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionStock.ASP/Areas/Security/Views/Authentication/ResetPassword.cshtml
@model GestionStock.ASP.Areas.Security.Models.Authentication.forms.ResetPasswordModel

@{
    ViewBag.Title = "Modification du mot de passe";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewPasssword, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.NewPasssword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPasssword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmNewPassword, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ConfirmNewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmNewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Renvoyer un email", "AskResetPassword")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}